SET REFERENTIAL_INTEGRITY FALSE;

DROP TABLE IF EXISTS fragrance_recipe_materials CASCADE;
DROP TABLE IF EXISTS inventory_transactions CASCADE;
DROP TABLE IF EXISTS reservations CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS audit_logs CASCADE;
DROP TABLE IF EXISTS fragrance_recipes CASCADE;
DROP TABLE IF EXISTS product_categories CASCADE;
DROP TABLE IF EXISTS inventory_items CASCADE;
DROP TABLE IF EXISTS experience_programs CASCADE;
DROP TABLE IF EXISTS customers CASCADE;
DROP TABLE IF EXISTS admin_users CASCADE;

SET REFERENTIAL_INTEGRITY TRUE;

CREATE TABLE admin_users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  is_active BOOLEAN,
  display_language VARCHAR(255),
  name VARCHAR(255) NOT NULL,
  email VARCHAR(255),
  login_id VARCHAR(255) NOT NULL,
  notification_setting VARCHAR(255),
  password_hash VARCHAR(255) NOT NULL,
  role VARCHAR(255) NOT NULL,
  CONSTRAINT pk_admin_users PRIMARY KEY (id),
  CONSTRAINT uk_admin_users_login_id UNIQUE (login_id)
);

CREATE TABLE customers (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  email VARCHAR(255) NOT NULL,
  name VARCHAR(255) NOT NULL,
  nationality VARCHAR(255),
  note VARCHAR(1000),
  phone VARCHAR(255),
  preferred_language VARCHAR(255),
  purpose VARCHAR(255),
  CONSTRAINT pk_customers PRIMARY KEY (id)
);

CREATE TABLE experience_programs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  is_active BOOLEAN,
  description VARCHAR(1000),
  duration_minutes INTEGER NOT NULL,
  material_summary VARCHAR(1000),
  name VARCHAR(255) NOT NULL,
  price NUMERIC(38, 2) NOT NULL,
  CONSTRAINT pk_experience_programs PRIMARY KEY (id)
);

CREATE TABLE inventory_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  category VARCHAR(255) NOT NULL,
  english_name VARCHAR(255),
  item_name VARCHAR(255) NOT NULL,
  last_stocked_date DATE,
  memo VARCHAR(1000),
  stock_quantity NUMERIC(38, 2) NOT NULL,
  storage_location VARCHAR(255),
  supplier VARCHAR(255),
  threshold_quantity NUMERIC(38, 2),
  unit VARCHAR(255) NOT NULL,
  CONSTRAINT pk_inventory_items PRIMARY KEY (id)
);

CREATE TABLE product_categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  is_active BOOLEAN,
  category_name VARCHAR(255) NOT NULL,
  display_order INTEGER NOT NULL,
  CONSTRAINT pk_product_categories PRIMARY KEY (id),
  CONSTRAINT uk_product_categories_category_name UNIQUE (category_name)
);

CREATE TABLE fragrance_recipes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  concept_note VARCHAR(1000),
  memo VARCHAR(1000),
  recipe_name VARCHAR(255) NOT NULL,
  total_amount NUMERIC(38, 2),
  customer_id BIGINT NOT NULL,
  CONSTRAINT pk_fragrance_recipes PRIMARY KEY (id),
  CONSTRAINT fk_fragrance_recipes_customer FOREIGN KEY (customer_id) REFERENCES customers (id)
);

CREATE TABLE fragrance_recipe_materials (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  amount NUMERIC(38, 2) NOT NULL,
  blend_ratio NUMERIC(38, 2) NOT NULL,
  display_order INTEGER,
  material_name_snapshot VARCHAR(255),
  fragrance_recipe_id BIGINT NOT NULL,
  inventory_item_id BIGINT NOT NULL,
  CONSTRAINT pk_fragrance_recipe_materials PRIMARY KEY (id),
  CONSTRAINT fk_recipe_materials_recipe FOREIGN KEY (fragrance_recipe_id) REFERENCES fragrance_recipes (id),
  CONSTRAINT fk_recipe_materials_inventory_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id)
);

CREATE TABLE inventory_transactions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  quantity NUMERIC(38, 2) NOT NULL,
  reason VARCHAR(1000),
  transaction_date DATE,
  transaction_type VARCHAR(255) NOT NULL,
  created_by BIGINT,
  inventory_item_id BIGINT NOT NULL,
  CONSTRAINT pk_inventory_transactions PRIMARY KEY (id),
  CONSTRAINT fk_inventory_transactions_admin FOREIGN KEY (created_by) REFERENCES admin_users (id),
  CONSTRAINT fk_inventory_transactions_item FOREIGN KEY (inventory_item_id) REFERENCES inventory_items (id)
);

CREATE TABLE products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  is_active BOOLEAN,
  category_id BIGINT NOT NULL,
  description VARCHAR(1000),
  english_name VARCHAR(255),
  price NUMERIC(38, 2) NOT NULL,
  product_name VARCHAR(255) NOT NULL,
  CONSTRAINT pk_products PRIMARY KEY (id),
  CONSTRAINT fk_products_category FOREIGN KEY (category_id) REFERENCES product_categories (id),
  CONSTRAINT fk_products_inventory_item_id FOREIGN KEY (id) REFERENCES inventory_items (id)
);

CREATE TABLE reservations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  number_of_people INTEGER NOT NULL,
  preferred_language VARCHAR(255),
  request_note VARCHAR(1000),
  status VARCHAR(255) NOT NULL,
  reservation_time VARCHAR(255) NOT NULL,
  reservation_date DATE NOT NULL,
  customer_id BIGINT NOT NULL,
  experience_program_id BIGINT NOT NULL,
  CONSTRAINT pk_reservations PRIMARY KEY (id),
  CONSTRAINT chk_reservations_number_of_people CHECK (number_of_people <= 4 AND number_of_people >= 1),
  CONSTRAINT fk_reservations_customer FOREIGN KEY (customer_id) REFERENCES customers (id),
  CONSTRAINT fk_reservations_experience_program FOREIGN KEY (experience_program_id) REFERENCES experience_programs (id)
);

CREATE TABLE audit_logs (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY DEFAULT ON NULL NOT NULL,
  created_at TIMESTAMP(6) NOT NULL,
  deleted_at TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL,
  action_type VARCHAR(255),
  description VARCHAR(1000),
  target_id BIGINT,
  target_table VARCHAR(255),
  admin_user_id BIGINT,
  CONSTRAINT pk_audit_logs PRIMARY KEY (id),
  CONSTRAINT fk_audit_logs_admin FOREIGN KEY (admin_user_id) REFERENCES admin_users (id)
);
